#!/bin/bash
#This program should accept 2 arguments, and rank them according to the year and gender given.
#Shadi El-Fares, 400525799
#Oct. 7th.24

if [[ $# -gt 2 ]];
then
	echo "You have entered the wrong number of arguments" >&2
	return 1;
#If we think about our ranges we have from 1880 and 2005, so it must match for 
elif [[ $1 =~ ^(18[8-9][0-9]|19[0-9]{2}|200[0-5])+$ ]];
then
	return 0;
elif [[ $1 == "--help" ]];
then
	echo -e "Title: BN \nVersion: 0.0.1 \n \nBrief Overview: This app takes in put year and letter (representing sex of baby name). \n \nUsage: To use correctly please enter the info like the following: \n\n./bn year f|F|m|M|b|B \n\nf|F - returns any year of a child within for female names.\n\nb|B - returns any year of a child within for boy names.\n\nyear - will index based on the file corresponding to that year." >&1
fi
